os: osx
sudo: false

osx_image:
  - xcode9.4
  - xcode10.3
  - xcode11.2
  
env:
  - LIBRARY=libadm VERSION=latest
  - LIBRARY=libbw64 VERSION=latest

before_install:
  - brew update >/dev/null

script:
  - |
    if [[ "${VERSION}" == "latest" ]]; then
      brew audit --strict --online ./${LIBRARY}.rb
      brew install ./${LIBRARY}.rb
      brew test ./${LIBRARY}.rb
    fi
