os: osx
sudo: false

osx_image:
  - xcode9.4
  - xcode10.3
  - xcode11.4

before_install:
  - brew update >/dev/null

script:
  -  brew audit --strict --online ./Formula/*.rb
  -  brew install ./Formula/*.rb
  -  brew test ./Formula/*.rb
